# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "external"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/hz.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🍥"
    subtitle = "数学研究无止境"
    avatar   = "img/hz.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "All Right Reserved, 河源中学数学研究协会"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "giscus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
    [comments.giscus]
    repo             = "HZMath/HZMath.github.io"
    repoID           = "R_kgDORsvlHQ"
    category         = "Comments"
    categoryID       = "DIC_kwDORsvlHc4C46et"
    mapping          = "title"
    lightTheme       = "light"
    darkTheme        = "dark_dimmed"
    reactionsEnabled = 1
    emitMetadata     = 0
    inputPosition    = "bottom"
    lang             = "zh-CN"
    strict           = 0
    loading          = "anonymous"

# <script src="https://giscus.app/client.js"
#         data-repo="HZMath/HZMath.github.io"
#         data-repo-id="R_kgDORsvlHQ"
#         data-category="Comments"
#         data-category-id="DIC_kwDORsvlHc4C46et"
#         data-mapping="title"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>
